plugin: aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: [running]
hostnames:
  - ip-address        # دي بتجيب الـ Private IP
  - public-ip-address # دي بتجيب الـ Public IP
compose:
  ansible_host: public_ip_address
